DROP TABLE IF EXISTS jobs;

CREATE TABLE IF NOT EXISTS jobs (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  company VARCHAR(45) NOT NULL,
  description VARCHAR(4096) NOT NULL,
  url VARCHAR(2048) NOT NULL,
  notes VARCHAR(1024) NULL,
  time_stamp DATETIME NOT NULL,
  applied DATETIME NULL
);


